[package]
name = "leptos_heavy_metal_stack"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
anyhow = "1.0.68"
console_log = "0.2.0"
console_error_panic_hook = "0.1.7"
futures = "0.3.25"
cfg-if = "1.0.0"
leptos = { path = "../leptos/leptos", default-features = false, features = [
	"serde",
] }
leptos_axum = { path = "../leptos/integrations/axum", default-features = false, optional = true }
leptos_config = { path = "../leptos/leptos_config", default-features = false}
leptos_meta = { path = "../leptos/meta",  default-features = false }
leptos_router = { path = "../leptos/router", default-features = false }
log = "0.4.17"
simple_logger = "4.0.0"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.91"
gloo-net = { version = "0.2.5", features = ["http"] }
reqwest = { version = "0.11.13", features = ["json"] }
axum = { version = "0.6.1", optional = true }
tower = { version = "0.4.13", optional = true }
tower-http = { version = "0.3.5", features = ["fs"], optional = true }
tokio = { version = "1.23.0", features = ["full"], optional = true }
http = { version = "0.2.8", optional = true }
sqlx = { version = "0.6.2", features = [
	"runtime-tokio-rustls",
	"sqlite",
], optional = true }
typed-builder = "0.11.0"

[features]
default = ["csr"]
leptos_autoreload = []
csr = ["leptos/csr", "leptos_meta/csr", "leptos_router/csr"]
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate"]
ssr = ["dep:axum", "dep:tower", "dep:tower-http", "dep:tokio", "dep:http", "dep:sqlx", "leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr", "leptos_axum"]

[package.metadata.cargo-all-features]
denylist = [
	"axum",
	"tower",
	"tower-http",
	"tokio",
	"http",
	"sqlx",
	"leptos_axum",
]
skip_feature_sets = [["csr", "ssr"], ["csr", "hydrate"], ["ssr", "hydrate"]]

[package.metadata.leptos]
# The name used by wasm-bindgen/cargo-leptos for the JS/WASM bundle. Defaults to the crate name   
package_name = "leptos_heavy_metal_stack"	
# The site root folder is where cargo-leptos generate all output. WARNING: all content of this folder will be erased on a rebuild. Use it in your server setup.
site_root = "target/site"
# The site_root relative folder where all compiled output (JS, WASM and CSS) is written
# Defaults to pkg	
site_pkg_dir = "pkg" 	
# [Optional] The source CSS file. If it ends with .sass or .scss then it will be compiled by dart-sass into CSS. The CSS is optimized by Lightning CSS before being written to <site_root>/<site_pkg>/app.css
# style_file = "src/styles/tailwind.css"
# [Optional] Files in the asset_dir will be copied to the site_root directory
assets_dir = "static/assets"
# The IP and port (ex: 127.0.0.1:3000) where the server serves the content. Use it in your server setup.
site_address = "127.0.0.1:3000"	
# The port to use for automatic reload monitoring
reload_port = 3001	
# [Optional] Command to use when running end2end tests. It will run in the end2end dir.
end2end_cmd = "npx playwright test"
#  The browserlist query used for optimizing the CSS.
browserquery = "defaults" 	
# Set by cargo-leptos watch when building with tha tool. Controls whether autoreload JS will be included in the head
watch = false 	
# The environment Leptos will run in, usually either "dev" or "prod"
env = "DEV"
